name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run tests
      run: npm test

    - name: Run linting
      run: npm run lint

    - name: Compile TypeScript
      run: npm run compile

    - name: Package extension
      run: npx @vscode/vsce package

    - name: Get version from tag
      id: get_version
      run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

    - name: Generate release notes
      id: release_notes
      run: |
        if [ -f CHANGELOG.md ]; then
          # Extract current version changes from CHANGELOG
          awk '/^## \['"${{ steps.get_version.outputs.VERSION }}"'\]/{flag=1; next} /^## \[/{flag=0} flag' CHANGELOG.md > release_notes.md
        else
          echo "Release version ${{ steps.get_version.outputs.VERSION }}" > release_notes.md
        fi

    - name: Generate checksum
      run: |
        sha256sum cursor-auto-resumer-${{ steps.get_version.outputs.VERSION }}.vsix > cursor-auto-resumer-${{ steps.get_version.outputs.VERSION }}.vsix.sha256

    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ github.ref }}
        name: Release ${{ steps.get_version.outputs.VERSION }}
        body_path: release_notes.md
        draft: false
        prerelease: false
        files: |
          cursor-auto-resumer-${{ steps.get_version.outputs.VERSION }}.vsix
          cursor-auto-resumer-${{ steps.get_version.outputs.VERSION }}.vsix.sha256
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Publish to VS Code Marketplace
      if: ${{ !contains(github.ref, 'beta') && !contains(github.ref, 'alpha') }}
      run: npx @vscode/vsce publish -p ${{ secrets.VSCE_PAT }}
      env:
        VSCE_PAT: ${{ secrets.VSCE_PAT }} 